# Generated by Django 3.2.7 on 2021-09-16 00:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210915_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='favorited_by',
            field=models.ManyToManyField(related_name='fav_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
