# Generated by Django 3.2.7 on 2021-09-16 00:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210916_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='favorited_by',
            field=models.ManyToManyField(related_name='fav_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
