# Generated by Django 3.2.7 on 2021-09-16 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210916_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='fav_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='fav_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='question', max_length=255),
            preserve_default=False,
        ),
    ]
